name: 'debug cmd'
on:
  push:
    branches:
      - 'nuitka-none'
      
  workflow_dispatch:

jobs:
  build_windows_x64:
    strategy:
      matrix:
        python-version:
          # - "3.10"
          # - "3.11"
          - "3.12"
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest]
        
    runs-on: ${{ matrix.os }}
    
    env:
      UV_SYSTEM_PYTHON: 1

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      # - name: Set up Python ${{ matrix.python-version }} with uv
      #   run: uv python install ${{ matrix.python-version }}        

      - name: "Set up Python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          # x86, x64, or arm64
          architecture: 'x64'
          # python-version-file: ".python-version"             

      - name: Install uv
        # https://docs.astral.sh/uv/guides/integration/github/#caching
        uses: astral-sh/setup-uv@v3
   
      - name: "List files"
        shell: cmd
        run: |
          pwd
          dir /s /b c:\

